"""
Comprehensive Technical Skill Taxonomy Dictionary.
Contains 450+ technology aliases, acronyms, tools, frameworks, databases, and competencies
mapped to clean canonical skill names.
"""

CANONICAL_SKILL_TAXONOMY: dict[str, str] = {
    # -------------------------------------------------------------------------
    # 1. Languages & Runtimes
    # -------------------------------------------------------------------------
    "python": "Python",
    "python3": "Python",
    "python 3": "Python",
    "py": "Python",
    "js": "JavaScript",
    "javascript": "JavaScript",
    "js/ts": "JavaScript",
    "es6": "JavaScript",
    "es6+": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "java": "Java",
    "java 8": "Java",
    "java 11": "Java",
    "java 17": "Java",
    "java 21": "Java",
    "c++": "C++",
    "cpp": "C++",
    "c": "C",
    "c#": "C#",
    "csharp": "C#",
    ".net": ".NET",
    "dotnet": ".NET",
    ".net core": ".NET Core",
    "dotnet core": ".NET Core",
    "ruby": "Ruby",
    "php": "PHP",
    "php8": "PHP",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "haskell": "Haskell",
    "clojure": "Clojure",
    "ocaml": "OCaml",
    "zig": "Zig",
    "dart": "Dart",
    "lua": "Lua",
    "perl": "Perl",
    "r": "R",
    "shell": "Shell/Bash",
    "bash": "Shell/Bash",
    "zsh": "Shell/Bash",
    "powershell": "PowerShell",
    "sql": "SQL",
    "pl/sql": "PL/SQL",
    "tsql": "T-SQL",
    "plpgsql": "PL/pgSQL",
    "html": "HTML5",
    "html5": "HTML5",
    "css": "CSS3",
    "css3": "CSS3",
    "sass": "Sass",
    "scss": "Sass",
    "less": "Less",
    # -------------------------------------------------------------------------
    # 2. Frontend Frameworks & Tools
    # -------------------------------------------------------------------------
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "react native": "React Native",
    "react-native": "React Native",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "next": "Next.js",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue 3": "Vue.js",
    "vue.js": "Vue.js",
    "nuxt": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "angular 2+": "Angular",
    "svelte": "Svelte",
    "svelte.js": "Svelte",
    "sveltekit": "SvelteKit",
    "vite": "Vite",
    "webpack": "Webpack",
    "rollup": "Rollup",
    "esbuild": "esbuild",
    "turbopack": "Turbopack",
    "babel": "Babel",
    "tailwindcss": "Tailwind CSS",
    "tailwind": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "MUI",
    "mui": "MUI",
    "chakra ui": "Chakra UI",
    "shadcn": "Shadcn UI",
    "shadcn/ui": "Shadcn UI",
    "styled-components": "Styled Components",
    "styled components": "Styled Components",
    "redux": "Redux",
    "redux toolkit": "Redux Toolkit",
    "pinia": "Pinia",
    "vuex": "Vuex",
    "zustand": "Zustand",
    "jotai": "Jotai",
    "recoil": "Recoil",
    "tanstack query": "TanStack Query",
    "react query": "TanStack Query",
    "swr": "SWR",
    "playwright": "Playwright",
    "cypress": "Cypress",
    "puppeteer": "Puppeteer",
    "jest": "Jest",
    "vitest": "Vitest",
    "testing library": "Testing Library",
    "storybook": "Storybook",
    # -------------------------------------------------------------------------
    # 3. Backend & APIs
    # -------------------------------------------------------------------------
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "django": "Django",
    "django rest framework": "Django REST Framework",
    "drf": "Django REST Framework",
    "flask": "Flask",
    "express": "Express.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "nestjs": "NestJS",
    "nest.js": "NestJS",
    "nest": "NestJS",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "bun": "Bun",
    "deno": "Deno",
    "spring": "Spring Boot",
    "spring boot": "Spring Boot",
    "spring framework": "Spring Boot",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "asp.net": "ASP.NET Core",
    "asp.net core": "ASP.NET Core",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "phoenix": "Phoenix",
    "gin": "Gin",
    "fiber": "Fiber",
    "actix": "Actix Web",
    "actix-web": "Actix Web",
    "axum": "Axum",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "rest": "REST API",
    "rest api": "REST API",
    "restful": "REST API",
    "restful apis": "REST API",
    "openapi": "OpenAPI / Swagger",
    "swagger": "OpenAPI / Swagger",
    "websockets": "WebSockets",
    "websocket": "WebSockets",
    "socket.io": "Socket.io",
    "oauth": "OAuth 2.0",
    "oauth2": "OAuth 2.0",
    "oauth 2.0": "OAuth 2.0",
    "jwt": "JWT",
    "json web tokens": "JWT",
    "pydantic": "Pydantic",
    "sqlalchemy": "SQLAlchemy",
    "prisma": "Prisma",
    "drizzle": "Prisma",
    "typeorm": "TypeORM",
    "hibernate": "Hibernate",
    "celery": "Celery",
    "rabbitmq": "RabbitMQ",
    "kafka": "Apache Kafka",
    "apache kafka": "Apache Kafka",
    "activemq": "ActiveMQ",
    "nats": "NATS",
    # -------------------------------------------------------------------------
    # 4. Databases & Caching
    # -------------------------------------------------------------------------
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "pg": "PostgreSQL",
    "pgvector": "pgvector",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "sqlite": "SQLite",
    "redis": "Redis",
    "valkey": "Redis",
    "memcached": "Memcached",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "dynamodb": "Amazon DynamoDB",
    "amazon dynamodb": "Amazon DynamoDB",
    "cassandra": "Apache Cassandra",
    "apache cassandra": "Apache Cassandra",
    "scylladb": "ScyllaDB",
    "cockroachdb": "CockroachDB",
    "yugabytedb": "YugabyteDB",
    "neo4j": "Neo4j",
    "arangodb": "ArangoDB",
    "elasticsearch": "Elasticsearch",
    "opensearch": "OpenSearch",
    "solr": "Apache Solr",
    "snowflake": "Snowflake",
    "bigquery": "Google BigQuery",
    "google bigquery": "Google BigQuery",
    "redshift": "Amazon Redshift",
    "amazon redshift": "Amazon Redshift",
    "clickhouse": "ClickHouse",
    "duckdb": "DuckDB",
    "databricks": "Databricks",
    "spark": "Apache Spark",
    "apache spark": "Apache Spark",
    "hadoop": "Apache Hadoop",
    "flink": "Apache Flink",
    # -------------------------------------------------------------------------
    # 5. Cloud & Infrastructure
    # -------------------------------------------------------------------------
    "aws": "AWS",
    "amazon web services": "AWS",
    "s3": "Amazon S3",
    "amazon s3": "Amazon S3",
    "ec2": "Amazon EC2",
    "amazon ec2": "Amazon EC2",
    "lambda": "AWS Lambda",
    "aws lambda": "AWS Lambda",
    "eks": "Amazon EKS",
    "amazon eks": "Amazon EKS",
    "ecs": "Amazon ECS",
    "amazon ecs": "Amazon ECS",
    "rds": "Amazon RDS",
    "amazon rds": "Amazon RDS",
    "cloudfront": "Amazon CloudFront",
    "iam": "AWS IAM",
    "aws iam": "AWS IAM",
    "gcp": "Google Cloud Platform (GCP)",
    "google cloud": "Google Cloud Platform (GCP)",
    "google cloud platform": "Google Cloud Platform (GCP)",
    "gke": "Google Kubernetes Engine (GKE)",
    "cloud run": "Google Cloud Run",
    "azure": "Microsoft Azure",
    "microsoft azure": "Microsoft Azure",
    "azure cloud": "Microsoft Azure",
    "aks": "Azure Kubernetes Service (AKS)",
    "cosmos db": "Azure Cosmos DB",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "docker": "Docker",
    "docker containers": "Docker",
    "containerization": "Docker",
    "podman": "Podman",
    "terraform": "Terraform",
    "opentofu": "Terraform",
    "pulumi": "Pulumi",
    "ansible": "Ansible",
    "puppet": "Puppet",
    "chef": "Chef",
    "linux": "Linux",
    "ubuntu": "Linux",
    "debian": "Linux",
    "alpine": "Linux",
    "redhat": "Linux",
    "rhel": "Linux",
    "centos": "Linux",
    "nginx": "Nginx",
    "apache": "Apache HTTP Server",
    "caddy": "Caddy",
    "traefik": "Traefik",
    "envoy": "Envoy Proxy",
    "cloudflare": "Cloudflare",
    "fastly": "Fastly",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "fly.io": "Fly.io",
    # -------------------------------------------------------------------------
    # 6. DevOps & CI/CD
    # -------------------------------------------------------------------------
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "continuous integration": "CI/CD",
    "continuous deployment": "CI/CD",
    "ci / cd pipelines": "CI/CD",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "gitlab": "GitLab CI",
    "jenkins": "Jenkins",
    "circleci": "CircleCI",
    "travis ci": "Travis CI",
    "argocd": "ArgoCD",
    "flux": "Flux CD",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "dynatrace": "Dynatrace",
    "sentry": "Sentry",
    "opentelemetry": "OpenTelemetry",
    "otel": "OpenTelemetry",
    "jaeger": "Jaeger",
    "zipkin": "Jaeger",
    "git": "Git",
    "github": "GitHub",
    "bitbucket": "Bitbucket",
    # -------------------------------------------------------------------------
    # 7. AI / ML / LLM / Vector Search
    # -------------------------------------------------------------------------
    "rag": "Retrieval-Augmented Generation (RAG)",
    "retrieval augmented generation": "Retrieval-Augmented Generation (RAG)",
    "retrieval-augmented generation": "Retrieval-Augmented Generation (RAG)",
    "vector embeddings retrieval augmented (rag)": "Retrieval-Augmented Generation (RAG)",
    "llm": "Large Language Models (LLM)",
    "llms": "Large Language Models (LLM)",
    "large language models": "Large Language Models (LLM)",
    "large language model": "Large Language Models (LLM)",
    "genai": "Generative AI",
    "generative ai": "Generative AI",
    "nlp": "Natural Language Processing (NLP)",
    "natural language processing": "Natural Language Processing (NLP)",
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "ai": "Artificial Intelligence (AI)",
    "artificial intelligence": "Artificial Intelligence (AI)",
    "deep learning": "Deep Learning",
    "computer vision": "Computer Vision",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "tensor flow": "TensorFlow",
    "tf": "TensorFlow",
    "keras": "Keras",
    "scikit-learn": "scikit-learn",
    "scikitlearn": "scikit-learn",
    "sklearn": "scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "huggingface": "Hugging Face",
    "hugging face": "Hugging Face",
    "langchain": "LangChain",
    "langgraph": "LangGraph",
    "llamaindex": "LlamaIndex",
    "llama index": "LlamaIndex",
    "openai": "OpenAI API",
    "openai api": "OpenAI API",
    "anthropic": "Anthropic Claude",
    "claude": "Anthropic Claude",
    "gemini": "Google Gemini",
    "ollama": "Ollama",
    "lm studio": "LM Studio",
    "vector search": "Vector Search",
    "vector databases": "Vector Search",
    "vector database": "Vector Search",
    "pinecone": "Pinecone",
    "weaviate": "Weaviate",
    "qdrant": "Qdrant",
    "chromadb": "ChromaDB",
    "chroma": "ChromaDB",
    "milvus": "Milvus",
    "faiss": "Faiss",
    # -------------------------------------------------------------------------
    # 8. Architecture & Software Practices
    # -------------------------------------------------------------------------
    "microservices": "Microservices",
    "microservice architecture": "Microservices",
    "distributed systems": "Distributed Systems",
    "event-driven architecture": "Event-Driven Architecture",
    "event driven architecture": "Event-Driven Architecture",
    "domain-driven design": "Domain-Driven Design (DDD)",
    "ddd": "Domain-Driven Design (DDD)",
    "system design": "System Design",
    "serverless": "Serverless",
    "tdd": "Test-Driven Development (TDD)",
    "test-driven development": "Test-Driven Development (TDD)",
    "bdd": "Behavior-Driven Development (BDD)",
    "agile": "Agile",
    "scrum": "Agile / Scrum",
    "kanban": "Kanban",
    "devops": "DevOps",
    "devsecops": "DevSecOps",
    "mlops": "MLOps",
    "site reliability engineering": "Site Reliability Engineering (SRE)",
    "sre": "Site Reliability Engineering (SRE)",
    "ci/cd pipelines": "CI/CD",
}
