"""Add LLM Judge fields to system_settings

Revision ID: 1eebe7b09947
Revises: b3c4d5e6f7a8
Create Date: 2026-09-16 23:59:57.686017

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1eebe7b09947"
down_revision: str | None = "b3c4d5e6f7a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_table("checkpoint_migrations")
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index(
        op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes"
    )
    op.drop_table("checkpoint_writes")
    op.drop_table("email_prompts")
    op.alter_column(
        "ai_providers",
        "engine_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Text(),
        existing_nullable=True,
        existing_server_default=sa.text("'auto'::character varying"),
    )
    op.drop_index(
        op.f("idx_email_application_events_conversation_id"),
        table_name="application_events",
    )
    op.drop_index(
        op.f("idx_email_application_events_received_at"),
        table_name="application_events",
    )
    op.drop_index(
        op.f("idx_email_application_events_type"), table_name="application_events"
    )
    op.create_index(
        "idx_application_events_conversation_id",
        "application_events",
        ["email_conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_application_events_received_at",
        "application_events",
        ["email_received_at"],
        unique=False,
    )
    op.create_index(
        "idx_application_events_type",
        "application_events",
        ["email_event_type"],
        unique=False,
    )
    op.drop_index(op.f("idx_email_other_events_type"), table_name="other_events")
    op.create_index(
        "idx_other_events_type", "other_events", ["email_type"], unique=False
    )
    op.add_column(
        "system_settings", sa.Column("enable_llm_judge", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "system_settings",
        sa.Column("llm_judge_audit_cover_letter", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column("llm_judge_audit_application_qa", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column("llm_judge_audit_interview_guide", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column("llm_judge_action", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column("llm_judge_max_retries", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_settings", "llm_judge_max_retries")
    op.drop_column("system_settings", "llm_judge_action")
    op.drop_column("system_settings", "llm_judge_audit_interview_guide")
    op.drop_column("system_settings", "llm_judge_audit_application_qa")
    op.drop_column("system_settings", "llm_judge_audit_cover_letter")
    op.drop_column("system_settings", "enable_llm_judge")
    op.drop_index("idx_other_events_type", table_name="other_events")
    op.create_index(
        op.f("idx_email_other_events_type"),
        "other_events",
        ["email_type"],
        unique=False,
    )
    op.drop_index("idx_application_events_type", table_name="application_events")
    op.drop_index("idx_application_events_received_at", table_name="application_events")
    op.drop_index(
        "idx_application_events_conversation_id", table_name="application_events"
    )
    op.create_index(
        op.f("idx_email_application_events_type"),
        "application_events",
        ["email_event_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_email_application_events_received_at"),
        "application_events",
        ["email_received_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_email_application_events_conversation_id"),
        "application_events",
        ["email_conversation_id"],
        unique=False,
    )
    op.alter_column(
        "ai_providers",
        "engine_type",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        existing_server_default=sa.text("'auto'::character varying"),
    )
    op.create_table(
        "email_prompts",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("template", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("email_prompts_pkey")),
    )
    op.create_table(
        "checkpoint_writes",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("idx", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column(
            "task_path",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "checkpoint_id",
            "task_id",
            "idx",
            name=op.f("checkpoint_writes_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_writes_thread_id_idx"),
        "checkpoint_writes",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoint_blobs",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("channel", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("blob", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "thread_id",
            "checkpoint_ns",
            "channel",
            "version",
            name=op.f("checkpoint_blobs_pkey"),
        ),
    )
    op.create_index(
        op.f("checkpoint_blobs_thread_id_idx"),
        "checkpoint_blobs",
        ["thread_id"],
        unique=False,
    )
    op.create_table(
        "checkpoint_migrations",
        sa.Column("v", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("v", name=op.f("checkpoint_migrations_pkey")),
    )
    op.create_table(
        "checkpoints",
        sa.Column("thread_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "checkpoint_ns",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("checkpoint_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "parent_checkpoint_id", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "checkpoint",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_ns", "checkpoint_id", name=op.f("checkpoints_pkey")
        ),
    )
    op.create_index(
        op.f("checkpoints_thread_id_idx"), "checkpoints", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###
