"""align schema with current models

Revision ID: f66de35140ce
Revises: 0001_initial
Create Date: 2026-08-19 16:48:00.330363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66de35140ce"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_llm_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("provider_name", sa.Text(), nullable=False),
        sa.Column("api_base", sa.Text(), nullable=True),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("embedding_model_name", sa.Text(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=True),
        sa.Column("top_p", sa.Float(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("agent_model_name", sa.Text(), nullable=True),
        sa.Column("agent_temperature", sa.Float(), nullable=False),
        sa.Column("agent_top_k", sa.Integer(), nullable=True),
        sa.Column("agent_top_p", sa.Float(), nullable=True),
        sa.Column("agent_max_tokens", sa.Integer(), nullable=True),
        sa.Column("agent_max_recursions", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email_other_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email_message_id", sa.Text(), nullable=True),
        sa.Column("email_internet_message_id", sa.Text(), nullable=True),
        sa.Column("email_conversation_id", sa.Text(), nullable=True),
        sa.Column("email_sender", sa.Text(), nullable=True),
        sa.Column("email_sender_name", sa.Text(), nullable=True),
        sa.Column("email_subject", sa.Text(), nullable=True),
        sa.Column("email_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_type", sa.Text(), nullable=False),
        sa.Column("company", sa.Text(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column(
            "action_required",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("raw_body", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_internet_message_id"),
        sa.UniqueConstraint("email_message_id"),
    )
    op.create_index(
        "idx_email_other_events_action_required",
        "email_other_events",
        ["action_required"],
        unique=False,
        postgresql_where=sa.text("action_required = TRUE"),
    )
    op.create_index(
        "idx_email_other_events_conversation_id",
        "email_other_events",
        ["email_conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_email_other_events_received_at",
        "email_other_events",
        ["email_received_at"],
        unique=False,
    )
    op.create_index(
        "idx_email_other_events_type",
        "email_other_events",
        ["email_type"],
        unique=False,
    )
    op.create_table(
        "processed_email_ids",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.String(length=512), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["email_accounts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", name="uq_processed_email_message_id"),
    )
    op.create_index(
        op.f("ix_processed_email_ids_account_id"),
        "processed_email_ids",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_email_ids_message_id"),
        "processed_email_ids",
        ["message_id"],
        unique=False,
    )
    op.create_table(
        "email_application_embeddings",
        sa.Column("email_application_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("embedding", Vector(dim=768), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_application_id"], ["email_applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("email_application_id"),
    )
    op.create_index(
        "email_application_embeddings_idx",
        "email_application_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("email_processed_messages")
    op.drop_table("llm_configs")
    op.drop_table("application_embeddings")
    op.add_column(
        "action_items", sa.Column("application_id", sa.BigInteger(), nullable=True)
    )
    op.add_column("action_items", sa.Column("event_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "action_items",
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
    )
    op.add_column("action_items", sa.Column("action_url", sa.Text(), nullable=True))
    op.add_column(
        "action_items",
        sa.Column("urgency", sa.Text(), server_default="MEDIUM", nullable=True),
    )
    op.add_column(
        "action_items", sa.Column("manual_urgency_override", sa.Text(), nullable=True)
    )
    op.create_index(
        "idx_action_items_application_id",
        "action_items",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "idx_action_items_event_id", "action_items", ["event_id"], unique=False
    )
    op.create_index("idx_action_items_status", "action_items", ["status"], unique=False)
    op.drop_constraint(
        op.f("action_items_email_application_event_id_fkey"),
        "action_items",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("action_items_email_application_id_fkey"),
        "action_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "action_items",
        "email_application_events",
        ["event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "action_items",
        "email_applications",
        ["application_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("action_items", "description")
    op.drop_column("action_items", "completed_at")
    op.drop_column("action_items", "is_completed")
    op.drop_column("action_items", "email_application_id")
    op.drop_column("action_items", "email_application_event_id")
    op.add_column(
        "candidate_cvs",
        sa.Column(
            "domain_experience",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_cvs",
        sa.Column(
            "core_competencies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_cvs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_cvs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("candidate_cvs", "file_name")
    op.drop_column("candidate_cvs", "parsed_at")
    op.drop_column("candidate_cvs", "file_hash")
    op.add_column("email_accounts", sa.Column("sync_cursor", sa.Text(), nullable=True))
    op.alter_column(
        "email_accounts",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "email_accounts",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "email_accounts",
        "username",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "email_accounts",
        "sync_interval",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'1h'::character varying"),
    )
    op.drop_constraint(
        op.f("email_accounts_email_address_key"), "email_accounts", type_="unique"
    )
    op.drop_column("email_accounts", "updated_at")
    op.drop_column("email_accounts", "email_address")
    op.alter_column(
        "email_application_events",
        "email_action_required",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_index(
        "idx_email_application_events_application_id",
        "email_application_events",
        ["email_application_id"],
        unique=False,
    )
    op.create_index(
        "idx_email_application_events_conversation_id",
        "email_application_events",
        ["email_conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_email_application_events_received_at",
        "email_application_events",
        ["email_received_at"],
        unique=False,
    )
    op.create_index(
        "idx_email_application_events_type",
        "email_application_events",
        ["email_event_type"],
        unique=False,
    )
    op.create_unique_constraint(
        None, "email_application_events", ["email_internet_message_id"]
    )
    op.create_unique_constraint(None, "email_application_events", ["email_message_id"])
    op.add_column(
        "email_applications",
        sa.Column(
            "match_analysis_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.alter_column(
        "email_applications", "position", existing_type=sa.TEXT(), nullable=True
    )
    op.create_index(
        "idx_email_applications_application_key",
        "email_applications",
        ["application_key"],
        unique=False,
    )
    op.create_index(
        "idx_email_applications_company_id",
        "email_applications",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "idx_email_applications_external_job_id",
        "email_applications",
        ["external_job_id"],
        unique=False,
    )
    op.create_index(
        "idx_email_applications_position_normalized",
        "email_applications",
        ["position_normalized"],
        unique=False,
    )
    op.create_index(
        "idx_email_applications_status", "email_applications", ["status"], unique=False
    )
    op.alter_column(
        "email_staging_items",
        "extracted_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.create_index(
        "idx_email_staging_items_conversation_id",
        "email_staging_items",
        ["email_conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_email_staging_items_received_at",
        "email_staging_items",
        ["email_received_at"],
        unique=False,
    )
    op.create_index(
        "idx_email_staging_items_status",
        "email_staging_items",
        ["status"],
        unique=False,
    )
    op.create_unique_constraint(
        None, "email_staging_items", ["email_internet_message_id"]
    )
    op.create_unique_constraint(None, "email_staging_items", ["email_message_id"])
    op.drop_constraint(
        op.f("email_staging_items_email_account_id_fkey"),
        "email_staging_items",
        type_="foreignkey",
    )
    op.create_index(
        op.f("ix_intake_evaluation_tasks_status"),
        "intake_evaluation_tasks",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intake_evaluation_tasks_task_type"),
        "intake_evaluation_tasks",
        ["task_type"],
        unique=False,
    )
    op.drop_column("intake_evaluation_tasks", "updated_at")
    op.add_column(
        "job_postings", sa.Column("application_id", sa.BigInteger(), nullable=True)
    )
    op.add_column("job_postings", sa.Column("job_url", sa.Text(), nullable=False))
    op.alter_column(
        "job_postings",
        "required_skills",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_constraint(
        op.f("job_postings_email_application_id_key"), "job_postings", type_="unique"
    )
    op.create_index(
        "idx_job_postings_application_id",
        "job_postings",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "idx_job_postings_job_url", "job_postings", ["job_url"], unique=False
    )
    op.drop_constraint(
        op.f("job_postings_email_application_id_fkey"),
        "job_postings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "job_postings",
        "email_applications",
        ["application_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("job_postings", "email_application_id")
    op.create_index(
        op.f("ix_trace_events_timestamp"), "trace_events", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trace_events_timestamp"), table_name="trace_events")
    op.add_column(
        "job_postings",
        sa.Column(
            "email_application_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "job_postings", type_="foreignkey")
    op.create_foreign_key(
        op.f("job_postings_email_application_id_fkey"),
        "job_postings",
        "email_applications",
        ["email_application_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("idx_job_postings_job_url", table_name="job_postings")
    op.drop_index("idx_job_postings_application_id", table_name="job_postings")
    op.create_unique_constraint(
        op.f("job_postings_email_application_id_key"),
        "job_postings",
        ["email_application_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "job_postings",
        "required_skills",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_column("job_postings", "job_url")
    op.drop_column("job_postings", "application_id")
    op.add_column(
        "intake_evaluation_tasks",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ix_intake_evaluation_tasks_task_type"),
        table_name="intake_evaluation_tasks",
    )
    op.drop_index(
        op.f("ix_intake_evaluation_tasks_status"), table_name="intake_evaluation_tasks"
    )
    op.create_foreign_key(
        op.f("email_staging_items_email_account_id_fkey"),
        "email_staging_items",
        "email_accounts",
        ["email_account_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "email_staging_items", type_="unique")
    op.drop_constraint(None, "email_staging_items", type_="unique")
    op.drop_index("idx_email_staging_items_status", table_name="email_staging_items")
    op.drop_index(
        "idx_email_staging_items_received_at", table_name="email_staging_items"
    )
    op.drop_index(
        "idx_email_staging_items_conversation_id", table_name="email_staging_items"
    )
    op.alter_column(
        "email_staging_items",
        "extracted_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index("idx_email_applications_status", table_name="email_applications")
    op.drop_index(
        "idx_email_applications_position_normalized", table_name="email_applications"
    )
    op.drop_index(
        "idx_email_applications_external_job_id", table_name="email_applications"
    )
    op.drop_index("idx_email_applications_company_id", table_name="email_applications")
    op.drop_index(
        "idx_email_applications_application_key", table_name="email_applications"
    )
    op.alter_column(
        "email_applications", "position", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("email_applications", "match_analysis_payload")
    op.drop_constraint(None, "email_application_events", type_="unique")
    op.drop_constraint(None, "email_application_events", type_="unique")
    op.drop_index(
        "idx_email_application_events_type", table_name="email_application_events"
    )
    op.drop_index(
        "idx_email_application_events_received_at",
        table_name="email_application_events",
    )
    op.drop_index(
        "idx_email_application_events_conversation_id",
        table_name="email_application_events",
    )
    op.drop_index(
        "idx_email_application_events_application_id",
        table_name="email_application_events",
    )
    op.alter_column(
        "email_application_events",
        "email_action_required",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.add_column(
        "email_accounts",
        sa.Column(
            "email_address", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "email_accounts",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        op.f("email_accounts_email_address_key"),
        "email_accounts",
        ["email_address"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "email_accounts",
        "sync_interval",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'1h'::character varying"),
    )
    op.alter_column(
        "email_accounts",
        "username",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "email_accounts",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "email_accounts",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("email_accounts", "sync_cursor")
    op.add_column(
        "candidate_cvs",
        sa.Column("file_hash", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "candidate_cvs",
        sa.Column(
            "parsed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_cvs",
        sa.Column("file_name", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("candidate_cvs", "updated_at")
    op.drop_column("candidate_cvs", "created_at")
    op.drop_column("candidate_cvs", "core_competencies")
    op.drop_column("candidate_cvs", "domain_experience")
    op.add_column(
        "action_items",
        sa.Column(
            "email_application_event_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "action_items",
        sa.Column(
            "email_application_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "action_items",
        sa.Column(
            "is_completed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "action_items",
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "action_items",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "action_items", type_="foreignkey")
    op.drop_constraint(None, "action_items", type_="foreignkey")
    op.create_foreign_key(
        op.f("action_items_email_application_id_fkey"),
        "action_items",
        "email_applications",
        ["email_application_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("action_items_email_application_event_id_fkey"),
        "action_items",
        "email_application_events",
        ["email_application_event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index("idx_action_items_status", table_name="action_items")
    op.drop_index("idx_action_items_event_id", table_name="action_items")
    op.drop_index("idx_action_items_application_id", table_name="action_items")
    op.drop_column("action_items", "manual_urgency_override")
    op.drop_column("action_items", "urgency")
    op.drop_column("action_items", "action_url")
    op.drop_column("action_items", "status")
    op.drop_column("action_items", "event_id")
    op.drop_column("action_items", "application_id")
    op.create_table(
        "application_embeddings",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "email_application_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "embedding",
            Vector(dim=768),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_application_id"],
            ["email_applications.id"],
            name=op.f("application_embeddings_email_application_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("application_embeddings_pkey")),
        sa.UniqueConstraint(
            "email_application_id",
            name=op.f("application_embeddings_email_application_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "llm_configs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("model_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "temperature",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0.2'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_default",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("llm_configs_pkey")),
    )
    op.create_table(
        "email_processed_messages",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("email_account_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "message_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "processed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_account_id"],
            ["email_accounts.id"],
            name=op.f("email_processed_messages_email_account_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_processed_messages_pkey")),
        sa.UniqueConstraint(
            "email_account_id",
            "message_id",
            name=op.f("uix_account_message"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(
        "email_application_embeddings_idx",
        table_name="email_application_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("email_application_embeddings")
    op.drop_index(
        op.f("ix_processed_email_ids_message_id"), table_name="processed_email_ids"
    )
    op.drop_index(
        op.f("ix_processed_email_ids_account_id"), table_name="processed_email_ids"
    )
    op.drop_table("processed_email_ids")
    op.drop_index("idx_email_other_events_type", table_name="email_other_events")
    op.drop_index("idx_email_other_events_received_at", table_name="email_other_events")
    op.drop_index(
        "idx_email_other_events_conversation_id", table_name="email_other_events"
    )
    op.drop_index(
        "idx_email_other_events_action_required",
        table_name="email_other_events",
        postgresql_where=sa.text("action_required = TRUE"),
    )
    op.drop_table("email_other_events")
    op.drop_table("email_llm_configs")
    # ### end Alembic commands ###
