server {
    listen 9377;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location / {
        set $scraper_upstream http://scraper:9377;
        proxy_pass $scraper_upstream;
        proxy_set_header Host $host;
        proxy_read_timeout 40s;
    }
}
